version: "3"

services:
  caddy:
    image: caddy:2-alpine
    container_name: caddy
    hostname: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - MY_DOMAIN
      - MY_EMAIL
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./data/caddy:/data
      - ./config/caddy:/config
      - ./logs:/logs

  bitwarden:
    image: vaultwarden/server:latest
    container_name: bitwarden
    hostname: bitwarden
    restart: unless-stopped
    environment:
      - SIGNUPS_ALLOWED
      - ADMIN_TOKEN
    volumes:
      - ./data/bitwarden:/data

  mariadb:
    image: mariadb:10.11
    container_name: mariadb
    hostname: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data/nextcloud-db:/var/lib/mysql

  nextcloud:
    image: nextcloud:30-apache
    container_name: nextcloud
    hostname: nextcloud
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data/nextcloud:/var/www/html/data
      - ./config/nexcloud:/var/www/html/config
    depends_on:
      - mariadb
